/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextPane;

/**
 *
 * @author Deking
 */
public class Bertarung extends javax.swing.JFrame {

    /**
     * Creates new form Bertarung
     */
    public Bertarung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelPlayer = new javax.swing.JPanel();
        serangBtn = new javax.swing.JButton();
        bertahanBtn = new javax.swing.JButton();
        skillsBtn = new javax.swing.JButton();
        namaLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HPLbl = new javax.swing.JLabel();
        ATTLbl = new javax.swing.JLabel();
        DEFLbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tahanLbl = new javax.swing.JLabel();
        titikPuncakLbl = new javax.swing.JLabel();
        LVLbl = new javax.swing.JLabel();
        backgroundPnl = new javax.swing.JPanel();
        panelNyerang = new javax.swing.JPanel();
        randomDEFLbl = new javax.swing.JLabel();
        randomATTLbl = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        namaLbl1 = new javax.swing.JLabel();
        musuhPnl = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        musuhHPLbl = new javax.swing.JLabel();
        musuhATTLbl = new javax.swing.JLabel();
        musuhDEFLbl = new javax.swing.JLabel();
        musuhLVLbl = new javax.swing.JLabel();
        musuhNamaLbl = new javax.swing.JLabel();
        keteranganTxt = new javax.swing.JTextPane();
        panelNyerang1 = new javax.swing.JPanel();
        randomDEFLbl1 = new javax.swing.JLabel();
        randomATTLbl1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        musuhNamaLbl1 = new javax.swing.JLabel();
        keteranganTxt1 = new javax.swing.JTextPane();

        jLabel5.setText("jLabel5");

        jLabel11.setText("jLabel11");

        jLabel14.setText("jLabel14");

        jLabel16.setText("jLabel16");

        jLabel18.setText("jLabel18");

        jLabel19.setBackground(java.awt.Color.black);
        jLabel19.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("NamaMonsterLawan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.black);
        jPanel1.setForeground(java.awt.Color.white);

        panelPlayer.setBackground(java.awt.Color.black);
        panelPlayer.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 5, true));
        panelPlayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serangBtn.setBackground(java.awt.Color.black);
        serangBtn.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        serangBtn.setForeground(java.awt.Color.white);
        serangBtn.setText("Serang");
        panelPlayer.add(serangBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        bertahanBtn.setBackground(java.awt.Color.black);
        bertahanBtn.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        bertahanBtn.setForeground(java.awt.Color.white);
        bertahanBtn.setText("Bertahan");
        panelPlayer.add(bertahanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        skillsBtn.setBackground(java.awt.Color.black);
        skillsBtn.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        skillsBtn.setForeground(java.awt.Color.white);
        skillsBtn.setText("Skills");
        panelPlayer.add(skillsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, -1, -1));

        namaLbl.setBackground(java.awt.Color.black);
        namaLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        namaLbl.setForeground(java.awt.Color.white);
        namaLbl.setText("NamaMonster");
        panelPlayer.add(namaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setBackground(java.awt.Color.black);
        jLabel2.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("HP     :");
        panelPlayer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setBackground(java.awt.Color.black);
        jLabel3.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("ATT    :");
        panelPlayer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setBackground(java.awt.Color.black);
        jLabel4.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("DEF    :");
        panelPlayer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        HPLbl.setBackground(java.awt.Color.black);
        HPLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        HPLbl.setForeground(java.awt.Color.white);
        HPLbl.setText("0");
        panelPlayer.add(HPLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, -1));

        ATTLbl.setBackground(java.awt.Color.black);
        ATTLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        ATTLbl.setForeground(java.awt.Color.white);
        ATTLbl.setText("0");
        panelPlayer.add(ATTLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 110, -1));

        DEFLbl.setBackground(java.awt.Color.black);
        DEFLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        DEFLbl.setForeground(java.awt.Color.white);
        DEFLbl.setText("0");
        panelPlayer.add(DEFLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 130, -1));

        jLabel9.setBackground(java.awt.Color.black);
        jLabel9.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Tahan  :");
        panelPlayer.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel10.setBackground(java.awt.Color.black);
        jLabel10.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Titik Puncak :");
        panelPlayer.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        tahanLbl.setBackground(java.awt.Color.black);
        tahanLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        tahanLbl.setForeground(java.awt.Color.white);
        tahanLbl.setText("0%");
        panelPlayer.add(tahanLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 130, -1));

        titikPuncakLbl.setBackground(java.awt.Color.black);
        titikPuncakLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        titikPuncakLbl.setForeground(java.awt.Color.white);
        titikPuncakLbl.setText("0%");
        panelPlayer.add(titikPuncakLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 160, -1));

        LVLbl.setBackground(java.awt.Color.black);
        LVLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        LVLbl.setForeground(java.awt.Color.white);
        LVLbl.setText("LV");
        panelPlayer.add(LVLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        backgroundPnl.setBackground(java.awt.Color.black);
        backgroundPnl.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 5, true));
        backgroundPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNyerang.setBackground(java.awt.Color.black);
        panelNyerang.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 5, true));
        panelNyerang.setForeground(java.awt.Color.white);
        panelNyerang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        randomDEFLbl.setBackground(java.awt.Color.black);
        randomDEFLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        randomDEFLbl.setForeground(java.awt.Color.white);
        randomDEFLbl.setText("0");
        randomDEFLbl.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelNyerang.add(randomDEFLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 55, -1, -1));

        randomATTLbl.setBackground(java.awt.Color.black);
        randomATTLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        randomATTLbl.setForeground(java.awt.Color.white);
        randomATTLbl.setText("0");
        randomATTLbl.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelNyerang.add(randomATTLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 55, -1, -1));

        jLabel17.setBackground(java.awt.Color.black);
        jLabel17.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("Serang VS Bertahan");
        jLabel17.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelNyerang.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 18, -1, -1));

        jLabel30.setBackground(java.awt.Color.black);
        jLabel30.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel30.setForeground(java.awt.Color.white);
        jLabel30.setText("VS");
        jLabel30.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelNyerang.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 55, -1, -1));

        namaLbl1.setBackground(java.awt.Color.black);
        namaLbl1.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        namaLbl1.setForeground(java.awt.Color.white);
        namaLbl1.setText("NamaMonster");
        panelNyerang.add(namaLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 92, 370, -1));

        backgroundPnl.add(panelNyerang, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 143, 400, 140));

        musuhPnl.setBackground(java.awt.Color.black);
        musuhPnl.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 5, true));
        musuhPnl.setForeground(java.awt.Color.white);
        musuhPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(java.awt.Color.black);
        jLabel20.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("HP   :");
        musuhPnl.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel21.setBackground(java.awt.Color.black);
        jLabel21.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("ATT   :");
        musuhPnl.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel22.setBackground(java.awt.Color.black);
        jLabel22.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setText("DEF  :");
        musuhPnl.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        musuhHPLbl.setBackground(java.awt.Color.black);
        musuhHPLbl.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        musuhHPLbl.setForeground(java.awt.Color.white);
        musuhHPLbl.setText("0");
        musuhPnl.add(musuhHPLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 80, -1));

        musuhATTLbl.setBackground(java.awt.Color.black);
        musuhATTLbl.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        musuhATTLbl.setForeground(java.awt.Color.white);
        musuhATTLbl.setText("0");
        musuhPnl.add(musuhATTLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 80, -1));

        musuhDEFLbl.setBackground(java.awt.Color.black);
        musuhDEFLbl.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        musuhDEFLbl.setForeground(java.awt.Color.white);
        musuhDEFLbl.setText("0");
        musuhPnl.add(musuhDEFLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 70, -1));

        musuhLVLbl.setBackground(java.awt.Color.black);
        musuhLVLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        musuhLVLbl.setForeground(java.awt.Color.white);
        musuhLVLbl.setText("LV");
        musuhPnl.add(musuhLVLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 60, -1));

        musuhNamaLbl.setBackground(java.awt.Color.black);
        musuhNamaLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        musuhNamaLbl.setForeground(java.awt.Color.white);
        musuhNamaLbl.setText("NamaMonsterLawan");
        musuhPnl.add(musuhNamaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 10, 320, -1));

        backgroundPnl.add(musuhPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 18, 459, 99));

        keteranganTxt.setEditable(false);
        keteranganTxt.setBackground(java.awt.Color.black);
        keteranganTxt.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        keteranganTxt.setForeground(java.awt.Color.white);
        backgroundPnl.add(keteranganTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 296, 400, 167));

        panelNyerang1.setBackground(java.awt.Color.black);
        panelNyerang1.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 5, true));
        panelNyerang1.setForeground(java.awt.Color.white);
        panelNyerang1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        randomDEFLbl1.setBackground(java.awt.Color.black);
        randomDEFLbl1.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        randomDEFLbl1.setForeground(java.awt.Color.white);
        randomDEFLbl1.setText("0");
        randomDEFLbl1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelNyerang1.add(randomDEFLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 55, 80, -1));

        randomATTLbl1.setBackground(java.awt.Color.black);
        randomATTLbl1.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        randomATTLbl1.setForeground(java.awt.Color.white);
        randomATTLbl1.setText("0");
        randomATTLbl1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelNyerang1.add(randomATTLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 55, 60, -1));

        jLabel23.setBackground(java.awt.Color.black);
        jLabel23.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setText("Serang VS Bertahan");
        jLabel23.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelNyerang1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 18, -1, -1));

        jLabel31.setBackground(java.awt.Color.black);
        jLabel31.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel31.setForeground(java.awt.Color.white);
        jLabel31.setText("VS");
        jLabel31.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panelNyerang1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 55, -1, -1));

        musuhNamaLbl1.setBackground(java.awt.Color.black);
        musuhNamaLbl1.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        musuhNamaLbl1.setForeground(java.awt.Color.white);
        musuhNamaLbl1.setText("NamaMonsterLawan");
        panelNyerang1.add(musuhNamaLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 90, 380, -1));

        backgroundPnl.add(panelNyerang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 143, 400, 140));

        keteranganTxt1.setEditable(false);
        keteranganTxt1.setBackground(java.awt.Color.black);
        keteranganTxt1.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        keteranganTxt1.setForeground(java.awt.Color.white);
        backgroundPnl.add(keteranganTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 296, 400, 167));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(backgroundPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backgroundPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1000, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextPane getKeteranganTxt1() {
        return keteranganTxt1;
    }

    public void setKeteranganTxt1(JTextPane keteranganTxt1) {
        this.keteranganTxt1 = keteranganTxt1;
    }

    public JLabel getMusuhNamaLbl1() {
        return musuhNamaLbl1;
    }

    public void setMusuhNamaLbl1(JLabel musuhNamaLbl1) {
        this.musuhNamaLbl1 = musuhNamaLbl1;
    }

    public JLabel getNamaLbl1() {
        return namaLbl1;
    }

    public void setNamaLbl1(JLabel namaLbl1) {
        this.namaLbl1 = namaLbl1;
    }

    public JPanel getPanelNyerang1() {
        return panelNyerang1;
    }

    public void setPanelNyerang1(JPanel panelNyerang1) {
        this.panelNyerang1 = panelNyerang1;
    }

    public JLabel getRandomATTLbl1() {
        return randomATTLbl1;
    }

    public void setRandomATTLbl1(JLabel randomATTLbl1) {
        this.randomATTLbl1 = randomATTLbl1;
    }

    public JLabel getRandomDEFLbl1() {
        return randomDEFLbl1;
    }

    public void setRandomDEFLbl1(JLabel randomDEFLbl1) {
        this.randomDEFLbl1 = randomDEFLbl1;
    }

    public JLabel getATTLbl() {
        return ATTLbl;
    }

    public void setATTLbl(JLabel ATTLbl) {
        this.ATTLbl = ATTLbl;
    }

    public JLabel getDEFLbl() {
        return DEFLbl;
    }

    public void setDEFLbl(JLabel DEFLbl) {
        this.DEFLbl = DEFLbl;
    }

    public JLabel getHPLbl() {
        return HPLbl;
    }

    public JLabel getMusuhNamaLbl() {
        return musuhNamaLbl;
    }

    public void setMusuhNamaLbl(JLabel musuhNamaLbl) {
        this.musuhNamaLbl = musuhNamaLbl;
    }

    public JLabel getNamaLbl() {
        return namaLbl;
    }

    public void setNamaLbl(JLabel namaLbl) {
        this.namaLbl = namaLbl;
    }

    public void setHPLbl(JLabel HPLbl) {
        this.HPLbl = HPLbl;
    }

    public JLabel getLVLbl() {
        return LVLbl;
    }

    public JLabel getRandomDEFLbl() {
        return randomDEFLbl;
    }

    public void setRandomDEFLbl(JLabel randomDEFLbl) {
        this.randomDEFLbl = randomDEFLbl;
    }

    public JButton getSkillsBtn() {
        return skillsBtn;
    }

    public void setSkillsBtn(JButton skillsBtn) {
        this.skillsBtn = skillsBtn;
    }

    public void setLVLbl(JLabel LVLbl) {
        this.LVLbl = LVLbl;
    }

    public JPanel getBackgroundPnl() {
        return backgroundPnl;
    }

    public void setBackgroundPnl(JPanel backgroundPnl) {
        this.backgroundPnl = backgroundPnl;
    }

    public JButton getBertahanBtn() {
        return bertahanBtn;
    }

    public void setBertahanBtn(JButton bertahanBtn) {
        this.bertahanBtn = bertahanBtn;
    }

    public JTextPane getKeteranganTxt() {
        return keteranganTxt;
    }

    public void setKeteranganTxt(JTextPane keteranganTxt) {
        this.keteranganTxt = keteranganTxt;
    }

    public JLabel getMusuhATTLbl() {
        return musuhATTLbl;
    }

    public void setMusuhATTLbl(JLabel musuhATTLbl) {
        this.musuhATTLbl = musuhATTLbl;
    }

    public JLabel getMusuhDEFLbl() {
        return musuhDEFLbl;
    }

    public void setMusuhDEFLbl(JLabel musuhDEFLbl) {
        this.musuhDEFLbl = musuhDEFLbl;
    }

    public JLabel getMusuhHPLbl() {
        return musuhHPLbl;
    }

    public void setMusuhHPLbl(JLabel musuhHPLbl) {
        this.musuhHPLbl = musuhHPLbl;
    }

    public JLabel getMusuhLVLbl() {
        return musuhLVLbl;
    }

    public void setMusuhLVLbl(JLabel musuhLVLbl) {
        this.musuhLVLbl = musuhLVLbl;
    }

    public JPanel getMusuhPnl() {
        return musuhPnl;
    }

    public void setMusuhPnl(JPanel musuhPnl) {
        this.musuhPnl = musuhPnl;
    }

    public JPanel getPanelNyerang() {
        return panelNyerang;
    }

    public void setPanelNyerang(JPanel panelNyerang) {
        this.panelNyerang = panelNyerang;
    }

    public JLabel getRandomATTLbl() {
        return randomATTLbl;
    }

    public JPanel getPanelPlayer() {
        return panelPlayer;
    }

    public void setPanelPlayer(JPanel panelPlayer) {
        this.panelPlayer = panelPlayer;
    }

    public void setRandomATTLbl(JLabel randonATTLbl) {
        this.randomATTLbl = randonATTLbl;
    }

    public JButton getSerangBtn() {
        return serangBtn;
    }

    public void setSerangBtn(JButton serangBtn) {
        this.serangBtn = serangBtn;
    }

    public JLabel getTahanLbl() {
        return tahanLbl;
    }

    public void setTahanLbl(JLabel tahanLbl) {
        this.tahanLbl = tahanLbl;
    }

    public JLabel getTitikPuncakLbl() {
        return titikPuncakLbl;
    }

    public void setTitikPuncakLbl(JLabel titikPuncakLbl) {
        this.titikPuncakLbl = titikPuncakLbl;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ATTLbl;
    private javax.swing.JLabel DEFLbl;
    private javax.swing.JLabel HPLbl;
    private javax.swing.JLabel LVLbl;
    private javax.swing.JPanel backgroundPnl;
    private javax.swing.JButton bertahanBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextPane keteranganTxt;
    private javax.swing.JTextPane keteranganTxt1;
    private javax.swing.JLabel musuhATTLbl;
    private javax.swing.JLabel musuhDEFLbl;
    private javax.swing.JLabel musuhHPLbl;
    private javax.swing.JLabel musuhLVLbl;
    private javax.swing.JLabel musuhNamaLbl;
    private javax.swing.JLabel musuhNamaLbl1;
    private javax.swing.JPanel musuhPnl;
    private javax.swing.JLabel namaLbl;
    private javax.swing.JLabel namaLbl1;
    private javax.swing.JPanel panelNyerang;
    private javax.swing.JPanel panelNyerang1;
    private javax.swing.JPanel panelPlayer;
    private javax.swing.JLabel randomATTLbl;
    private javax.swing.JLabel randomATTLbl1;
    private javax.swing.JLabel randomDEFLbl;
    private javax.swing.JLabel randomDEFLbl1;
    private javax.swing.JButton serangBtn;
    private javax.swing.JButton skillsBtn;
    private javax.swing.JLabel tahanLbl;
    private javax.swing.JLabel titikPuncakLbl;
    // End of variables declaration//GEN-END:variables
}
