/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author Deking
 */
public class LevelUp extends javax.swing.JFrame {

    /**
     * Creates new form PembuatanMonster
     */
    public LevelUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        judulpembuatansilumanLbl = new javax.swing.JLabel();
        panelMonster2 = new javax.swing.JPanel();
        atributLbl2 = new javax.swing.JLabel();
        attLbl = new javax.swing.JLabel();
        defLbl = new javax.swing.JLabel();
        hpLbl = new javax.swing.JLabel();
        resetBtn2 = new javax.swing.JButton();
        pointsLbl2 = new javax.swing.JLabel();
        plusattBtn2 = new javax.swing.JButton();
        plusdefBtn2 = new javax.swing.JButton();
        plushpBtn2 = new javax.swing.JButton();
        intattLbl2 = new javax.swing.JLabel();
        intdefLbl2 = new javax.swing.JLabel();
        inthpLbl2 = new javax.swing.JLabel();
        intpointLbl2 = new javax.swing.JLabel();
        namaMonsterLbl2 = new javax.swing.JLabel();
        levelLbl2 = new javax.swing.JLabel();
        selesaiBtn = new javax.swing.JButton();
        panelMonster1 = new javax.swing.JPanel();
        atributLbl1 = new javax.swing.JLabel();
        attLbl1 = new javax.swing.JLabel();
        defLbl1 = new javax.swing.JLabel();
        hpLbl1 = new javax.swing.JLabel();
        resetBtn1 = new javax.swing.JButton();
        pointsLbl1 = new javax.swing.JLabel();
        plusattBtn1 = new javax.swing.JButton();
        plusdefBtn1 = new javax.swing.JButton();
        plushpBtn1 = new javax.swing.JButton();
        intattLbl1 = new javax.swing.JLabel();
        intdefLbl1 = new javax.swing.JLabel();
        inthpLbl1 = new javax.swing.JLabel();
        intpointLbl1 = new javax.swing.JLabel();
        namaMonsterLbl1 = new javax.swing.JLabel();
        levelLbl1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keteranganTxt = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));

        jPanel1.setBackground(java.awt.Color.black);
        jPanel1.setForeground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(java.awt.Color.black);
        jPanel5.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 5, true));
        jPanel5.setForeground(java.awt.Color.white);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judulpembuatansilumanLbl.setBackground(java.awt.Color.black);
        judulpembuatansilumanLbl.setFont(new java.awt.Font("Square721 BT", 1, 48)); // NOI18N
        judulpembuatansilumanLbl.setForeground(java.awt.Color.white);
        judulpembuatansilumanLbl.setText("Result");
        jPanel5.add(judulpembuatansilumanLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 940, 94));

        panelMonster2.setBackground(java.awt.Color.black);
        panelMonster2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white, 5));
        panelMonster2.setForeground(java.awt.Color.white);
        panelMonster2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atributLbl2.setBackground(java.awt.Color.black);
        atributLbl2.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        atributLbl2.setForeground(java.awt.Color.white);
        atributLbl2.setText("Atribut");
        panelMonster2.add(atributLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        attLbl.setBackground(java.awt.Color.black);
        attLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        attLbl.setForeground(java.awt.Color.white);
        attLbl.setText("Attack :");
        panelMonster2.add(attLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        defLbl.setBackground(java.awt.Color.black);
        defLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        defLbl.setForeground(java.awt.Color.white);
        defLbl.setText("Defend :");
        panelMonster2.add(defLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        hpLbl.setBackground(java.awt.Color.black);
        hpLbl.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        hpLbl.setForeground(java.awt.Color.white);
        hpLbl.setText("Health :");
        panelMonster2.add(hpLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        resetBtn2.setBackground(java.awt.Color.black);
        resetBtn2.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        resetBtn2.setForeground(java.awt.Color.white);
        resetBtn2.setText("Reset");
        panelMonster2.add(resetBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        pointsLbl2.setBackground(java.awt.Color.black);
        pointsLbl2.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        pointsLbl2.setForeground(java.awt.Color.white);
        pointsLbl2.setText("Points :");
        panelMonster2.add(pointsLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        plusattBtn2.setBackground(java.awt.Color.black);
        plusattBtn2.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        plusattBtn2.setForeground(java.awt.Color.white);
        plusattBtn2.setText("+");
        panelMonster2.add(plusattBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        plusdefBtn2.setBackground(java.awt.Color.black);
        plusdefBtn2.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        plusdefBtn2.setForeground(java.awt.Color.white);
        plusdefBtn2.setText("+");
        panelMonster2.add(plusdefBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        plushpBtn2.setBackground(java.awt.Color.black);
        plushpBtn2.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        plushpBtn2.setForeground(java.awt.Color.white);
        plushpBtn2.setText("+");
        panelMonster2.add(plushpBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        intattLbl2.setBackground(java.awt.Color.black);
        intattLbl2.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        intattLbl2.setForeground(java.awt.Color.white);
        intattLbl2.setText("0");
        panelMonster2.add(intattLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 150, -1));

        intdefLbl2.setBackground(java.awt.Color.black);
        intdefLbl2.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        intdefLbl2.setForeground(java.awt.Color.white);
        intdefLbl2.setText("0");
        panelMonster2.add(intdefLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, -1));

        inthpLbl2.setBackground(java.awt.Color.black);
        inthpLbl2.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        inthpLbl2.setForeground(java.awt.Color.white);
        inthpLbl2.setText("0");
        panelMonster2.add(inthpLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 120, -1));

        intpointLbl2.setBackground(java.awt.Color.black);
        intpointLbl2.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        intpointLbl2.setForeground(java.awt.Color.white);
        intpointLbl2.setText("0");
        panelMonster2.add(intpointLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, 30));

        namaMonsterLbl2.setBackground(java.awt.Color.black);
        namaMonsterLbl2.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        namaMonsterLbl2.setForeground(java.awt.Color.white);
        namaMonsterLbl2.setText("NamaMonster");
        panelMonster2.add(namaMonsterLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        levelLbl2.setBackground(java.awt.Color.black);
        levelLbl2.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        levelLbl2.setForeground(java.awt.Color.white);
        levelLbl2.setText("LV");
        panelMonster2.add(levelLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jPanel1.add(panelMonster2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 430, 370));

        selesaiBtn.setBackground(java.awt.Color.black);
        selesaiBtn.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        selesaiBtn.setForeground(java.awt.Color.white);
        selesaiBtn.setText("Kembali Ke Title");
        jPanel1.add(selesaiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        panelMonster1.setBackground(java.awt.Color.black);
        panelMonster1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white, 5));
        panelMonster1.setForeground(java.awt.Color.white);
        panelMonster1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atributLbl1.setBackground(java.awt.Color.black);
        atributLbl1.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        atributLbl1.setForeground(java.awt.Color.white);
        atributLbl1.setText("Atribut");
        panelMonster1.add(atributLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        attLbl1.setBackground(java.awt.Color.black);
        attLbl1.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        attLbl1.setForeground(java.awt.Color.white);
        attLbl1.setText("Attack :");
        panelMonster1.add(attLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        defLbl1.setBackground(java.awt.Color.black);
        defLbl1.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        defLbl1.setForeground(java.awt.Color.white);
        defLbl1.setText("Defend :");
        panelMonster1.add(defLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        hpLbl1.setBackground(java.awt.Color.black);
        hpLbl1.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        hpLbl1.setForeground(java.awt.Color.white);
        hpLbl1.setText("Health :");
        panelMonster1.add(hpLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        resetBtn1.setBackground(java.awt.Color.black);
        resetBtn1.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        resetBtn1.setForeground(java.awt.Color.white);
        resetBtn1.setText("Reset");
        panelMonster1.add(resetBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        pointsLbl1.setBackground(java.awt.Color.black);
        pointsLbl1.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        pointsLbl1.setForeground(java.awt.Color.white);
        pointsLbl1.setText("Points :");
        panelMonster1.add(pointsLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        plusattBtn1.setBackground(java.awt.Color.black);
        plusattBtn1.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        plusattBtn1.setForeground(java.awt.Color.white);
        plusattBtn1.setText("+");
        panelMonster1.add(plusattBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        plusdefBtn1.setBackground(java.awt.Color.black);
        plusdefBtn1.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        plusdefBtn1.setForeground(java.awt.Color.white);
        plusdefBtn1.setText("+");
        panelMonster1.add(plusdefBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        plushpBtn1.setBackground(java.awt.Color.black);
        plushpBtn1.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        plushpBtn1.setForeground(java.awt.Color.white);
        plushpBtn1.setText("+");
        panelMonster1.add(plushpBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        intattLbl1.setBackground(java.awt.Color.black);
        intattLbl1.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        intattLbl1.setForeground(java.awt.Color.white);
        intattLbl1.setText("0");
        panelMonster1.add(intattLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 150, -1));

        intdefLbl1.setBackground(java.awt.Color.black);
        intdefLbl1.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        intdefLbl1.setForeground(java.awt.Color.white);
        intdefLbl1.setText("0");
        panelMonster1.add(intdefLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, -1));

        inthpLbl1.setBackground(java.awt.Color.black);
        inthpLbl1.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        inthpLbl1.setForeground(java.awt.Color.white);
        inthpLbl1.setText("0");
        panelMonster1.add(inthpLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 120, -1));

        intpointLbl1.setBackground(java.awt.Color.black);
        intpointLbl1.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        intpointLbl1.setForeground(java.awt.Color.white);
        intpointLbl1.setText("0");
        panelMonster1.add(intpointLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, 30));

        namaMonsterLbl1.setBackground(java.awt.Color.black);
        namaMonsterLbl1.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        namaMonsterLbl1.setForeground(java.awt.Color.white);
        namaMonsterLbl1.setText("NamaMonster");
        panelMonster1.add(namaMonsterLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        levelLbl1.setBackground(java.awt.Color.black);
        levelLbl1.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        levelLbl1.setForeground(java.awt.Color.white);
        levelLbl1.setText("LV");
        panelMonster1.add(levelLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jPanel1.add(panelMonster1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 460, 370));

        jScrollPane1.setBackground(java.awt.Color.black);

        keteranganTxt.setEditable(false);
        keteranganTxt.setBackground(java.awt.Color.black);
        keteranganTxt.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        keteranganTxt.setForeground(java.awt.Color.white);
        jScrollPane1.setViewportView(keteranganTxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 900, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getIntattLbl1() {
        return intattLbl1;
    }

    public void setIntattLbl1(JLabel intattLbl1) {
        this.intattLbl1 = intattLbl1;
    }

    public JLabel getIntattLbl2() {
        return intattLbl2;
    }

    public void setIntattLbl2(JLabel intattLbl2) {
        this.intattLbl2 = intattLbl2;
    }

    public JLabel getIntdefLbl1() {
        return intdefLbl1;
    }

    public void setIntdefLbl1(JLabel intdefLbl1) {
        this.intdefLbl1 = intdefLbl1;
    }

    public JLabel getIntdefLbl2() {
        return intdefLbl2;
    }

    public void setIntdefLbl2(JLabel intdefLbl2) {
        this.intdefLbl2 = intdefLbl2;
    }

    public JLabel getInthpLbl1() {
        return inthpLbl1;
    }

    public void setInthpLbl1(JLabel inthpLbl1) {
        this.inthpLbl1 = inthpLbl1;
    }

    public JLabel getInthpLbl2() {
        return inthpLbl2;
    }

    public void setInthpLbl2(JLabel inthpLbl2) {
        this.inthpLbl2 = inthpLbl2;
    }

    public JLabel getIntpointLbl1() {
        return intpointLbl1;
    }

    public void setIntpointLbl1(JLabel intpointLbl1) {
        this.intpointLbl1 = intpointLbl1;
    }

    public JLabel getIntpointLbl2() {
        return intpointLbl2;
    }

    public void setIntpointLbl2(JLabel intpointLbl2) {
        this.intpointLbl2 = intpointLbl2;
    }

    public JTextPane getKeteranganTxt() {
        return keteranganTxt;
    }

    public void setKeteranganTxt(JTextPane keteranganTxt) {
        this.keteranganTxt = keteranganTxt;
    }

    public JLabel getLevelLbl1() {
        return levelLbl1;
    }

    public void setLevelLbl1(JLabel levelLbl1) {
        this.levelLbl1 = levelLbl1;
    }

    public JLabel getLevelLbl2() {
        return levelLbl2;
    }

    public void setLevelLbl2(JLabel levelLbl2) {
        this.levelLbl2 = levelLbl2;
    }

    public JLabel getNamaMonsterLbl1() {
        return namaMonsterLbl1;
    }

    public void setNamaMonsterLbl1(JLabel namaMonsterLbl1) {
        this.namaMonsterLbl1 = namaMonsterLbl1;
    }

    public JLabel getNamaMonsterLbl2() {
        return namaMonsterLbl2;
    }

    public void setNamaMonsterLbl2(JLabel namaMonsterLbl2) {
        this.namaMonsterLbl2 = namaMonsterLbl2;
    }

    public JPanel getPanelMonster1() {
        return panelMonster1;
    }

    public void setPanelMonster1(JPanel panelMonster1) {
        this.panelMonster1 = panelMonster1;
    }

    public JPanel getPanelMonster2() {
        return panelMonster2;
    }

    public void setPanelMonster2(JPanel panelMonster2) {
        this.panelMonster2 = panelMonster2;
    }

    public JButton getPlusattBtn1() {
        return plusattBtn1;
    }

    public void setPlusattBtn1(JButton plusattBtn1) {
        this.plusattBtn1 = plusattBtn1;
    }

    public JButton getPlusattBtn2() {
        return plusattBtn2;
    }

    public void setPlusattBtn2(JButton plusattBtn2) {
        this.plusattBtn2 = plusattBtn2;
    }

    public JButton getPlusdefBtn1() {
        return plusdefBtn1;
    }

    public void setPlusdefBtn1(JButton plusdefBtn1) {
        this.plusdefBtn1 = plusdefBtn1;
    }

    public JButton getPlusdefBtn2() {
        return plusdefBtn2;
    }

    public void setPlusdefBtn2(JButton plusdefBtn2) {
        this.plusdefBtn2 = plusdefBtn2;
    }

    public JButton getPlushpBtn1() {
        return plushpBtn1;
    }

    public void setPlushpBtn1(JButton plushpBtn1) {
        this.plushpBtn1 = plushpBtn1;
    }

    public JButton getPlushpBtn2() {
        return plushpBtn2;
    }

    public void setPlushpBtn2(JButton plushpBtn2) {
        this.plushpBtn2 = plushpBtn2;
    }

    public JButton getResetBtn1() {
        return resetBtn1;
    }

    public void setResetBtn1(JButton resetBtn1) {
        this.resetBtn1 = resetBtn1;
    }

    public JButton getResetBtn2() {
        return resetBtn2;
    }

    public void setResetBtn2(JButton resetBtn2) {
        this.resetBtn2 = resetBtn2;
    }

    public JButton getSelesaiBtn() {
        return selesaiBtn;
    }

    public void setSelesaiBtn(JButton selesaiBtn) {
        this.selesaiBtn = selesaiBtn;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atributLbl1;
    private javax.swing.JLabel atributLbl2;
    private javax.swing.JLabel attLbl;
    private javax.swing.JLabel attLbl1;
    private javax.swing.JLabel defLbl;
    private javax.swing.JLabel defLbl1;
    private javax.swing.JLabel hpLbl;
    private javax.swing.JLabel hpLbl1;
    private javax.swing.JLabel intattLbl1;
    private javax.swing.JLabel intattLbl2;
    private javax.swing.JLabel intdefLbl1;
    private javax.swing.JLabel intdefLbl2;
    private javax.swing.JLabel inthpLbl1;
    private javax.swing.JLabel inthpLbl2;
    private javax.swing.JLabel intpointLbl1;
    private javax.swing.JLabel intpointLbl2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulpembuatansilumanLbl;
    private javax.swing.JTextPane keteranganTxt;
    private javax.swing.JLabel levelLbl1;
    private javax.swing.JLabel levelLbl2;
    private javax.swing.JLabel namaMonsterLbl1;
    private javax.swing.JLabel namaMonsterLbl2;
    private javax.swing.JPanel panelMonster1;
    private javax.swing.JPanel panelMonster2;
    private javax.swing.JButton plusattBtn1;
    private javax.swing.JButton plusattBtn2;
    private javax.swing.JButton plusdefBtn1;
    private javax.swing.JButton plusdefBtn2;
    private javax.swing.JButton plushpBtn1;
    private javax.swing.JButton plushpBtn2;
    private javax.swing.JLabel pointsLbl1;
    private javax.swing.JLabel pointsLbl2;
    private javax.swing.JButton resetBtn1;
    private javax.swing.JButton resetBtn2;
    private javax.swing.JButton selesaiBtn;
    // End of variables declaration//GEN-END:variables
}
